[workspace]
resolver = "3"
members = [
    "crates/jerrycan",
    "crates/jerrycan-core",
    "crates/jerrycan-macros",
    "crates/jerrycan-db",
    "crates/jerrycan-auth",
    "crates/jerrycan-validate",
    "crates/jerrycan-observe",
    "crates/jerrycan-ratelimit",
    "crates/jerrycan-jobs",
]
exclude = ["fuzz"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://jerrycan.cc"
repository = "https://github.com/backant-io/jerrycan"
authors = ["Pavel Hegler"]
rust-version = "1.88"

[workspace.dependencies]
jerrycan-core = { path = "crates/jerrycan-core", version = "0.2.0" }
jerrycan-macros = { path = "crates/jerrycan-macros", version = "0.2.0" }
jerrycan-db = { path = "crates/jerrycan-db", version = "0.2.0" }
jerrycan-validate = { path = "crates/jerrycan-validate", version = "0.2.0" }
jerrycan-auth = { path = "crates/jerrycan-auth", version = "0.2.0" }
jerrycan-observe = { path = "crates/jerrycan-observe", version = "0.2.0" }
jerrycan-ratelimit = { path = "crates/jerrycan-ratelimit", version = "0.2.0" }
jerrycan-jobs = { path = "crates/jerrycan-jobs", version = "0.2.0" }
argon2 = "0.5"
chacha20poly1305 = "0.10"
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
base64 = "0.22"
rand = "0.8"
zeroize = "1"
redis = { version = "1", default-features = false, features = ["tokio-comp", "tokio-rustls-comp", "connection-manager", "script"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "any", "sqlite", "postgres"] }
sea-orm = { version = "1", default-features = false, features = ["runtime-tokio-rustls", "sqlx-sqlite", "sqlx-postgres", "macros", "with-json"] }
sea-query = { version = "0.32", default-features = false, features = ["backend-sqlite", "backend-postgres"] }
sea-query-binder = { version = "0.7", default-features = false, features = ["sqlx-any"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "time", "sync", "signal"] }
hyper = { version = "1", features = ["http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio", "server", "http1"] }
http = "1"
http-body = "1"
http-body-util = "0.1"
bytes = "1"
futures-core = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
criterion = { version = "0.5", features = ["html_reports"] }
