//! Generated acceptance tests: the design contract as runnable assertions.

use jerrycan::platform::design::Design;
use jerrycan::platform::testgen;

const GOLDEN: &str = include_str!("../../../conformance/designs/todo-api.design.json");

fn golden(db: bool) -> Design {
    let mut v: serde_json::Value = serde_json::from_str(GOLDEN).unwrap();
    if db {
        v["dependencies"] = serde_json::json!(["db"]);
    }
    serde_json::from_value(v).unwrap()
}

#[test]
fn memory_mode_tests_cover_success_and_listed_errors() {
    let design = golden(false);
    let module = &design.modules[0]; // todos (with comments subroute)
    let generated = testgen::acceptance_rs(&design, module);

    assert!(
        generated.contains("GENERATED by jerrycan gen-tests"),
        "tool-owned banner"
    );
    assert!(
        generated.contains("use route_todos::module;"),
        "{generated}"
    );
    // success tests:
    for expected in [
        "async fn list_todos_returns_200",
        "async fn create_todo_returns_201",
        "async fn show_todo_returns_200",
        "async fn delete_todo_returns_204",
        "async fn list_comments_returns_200",
        "async fn create_comment_returns_201",
    ] {
        assert!(
            generated.contains(expected),
            "missing {expected}\n{generated}"
        );
    }
    // listed 404s:
    assert!(
        generated.contains("async fn show_todo_missing_id_is_404"),
        "{generated}"
    );
    assert!(generated.contains("/todos/999999"), "{generated}");
    // seed-then-request flow uses the creator:
    assert!(generated.contains("post_json(\"/todos/\""), "{generated}");
    // memory preamble — no db:
    assert!(!generated.contains("jerrycan::db"), "{generated}");
    assert_eq!(
        testgen::test_count(&generated),
        8,
        "6 success + 2 listed 404s"
    );
}

#[test]
fn db_mode_preamble_migrates_an_in_memory_database() {
    let design = golden(true);
    let module = &design.modules[0];
    let generated = testgen::acceptance_rs(&design, module);
    assert!(
        generated.contains("Db::connect(\"sqlite::memory:\")"),
        "{generated}"
    );
    assert!(
        generated.contains("include_str!(\"../migrations/sqlite/0001_create_tables.sql\")"),
        "{generated}"
    );
    assert!(generated.contains(".extend(db)"), "{generated}");
}

#[test]
fn unsupported_error_cases_become_an_agent_todo_comment() {
    let mut design = golden(false);
    design.modules[0].endpoints[1]
        .errors
        .push(jerrycan::platform::design::ErrorCase {
            status: 409,
            code: Some("JC0409".into()),
            when: "duplicate title".into(),
        });
    let generated = testgen::acceptance_rs(&design, &design.modules[0].clone());
    assert!(
        generated.contains("// AGENT TODO: design lists 409 (duplicate title)"),
        "{generated}"
    );
}

/// A tenant-owned module's guarded handlers take `Dep<Tenant>`; the generated
/// test app must register the `tenant` factory and SEED a membership row, or the
/// guard 403s every guarded request (a false stub-test failure). WHY this matters:
/// the seed is what keeps these acceptance tests failing for the RIGHT reason
/// (stub-500), not an unseeded-membership 403. It must (a) migrate the tenant
/// module's tables (the `{tenant}_members` table the guard queries lives there),
/// (b) insert a tenant row whose enum column uses a DECLARED value so the CHECK
/// passes, and (c) insert the membership row, then provide the `tenant` factory.
#[test]
fn tenancy_module_tests_seed_membership_and_provide_the_guard() {
    let s = include_str!("../../../conformance/designs/kolli-slice.design.json");
    let design: Design = serde_json::from_str(s).unwrap();
    let leads = design
        .modules
        .iter()
        .find(|m| m.name == "leads")
        .expect("leads module");
    let generated = testgen::acceptance_rs(&design, leads);

    // The Tenant factory is registered app-wide for the guard to resolve.
    assert!(
        generated.contains(".provide_dep(shared::tenant)"),
        "{generated}"
    );
    // The tenant module's migration is pulled in (cross-crate) so the membership
    // table exists in this module's test database.
    assert!(
        generated.contains(
            "include_str!(\"../../workspaces/migrations/sqlite/0001_create_tables.sql\")"
        ),
        "tenant migration cross-included: {generated}"
    );
    // Seeds: a tenant row (enum `plan` uses a declared value, not 'test-value', so
    // the CHECK passes) and the membership row for user 1.
    assert!(
        generated.contains("INSERT INTO \\\"workspaces\\\"") && generated.contains("'trial'"),
        "tenant row seeded with a valid enum value: {generated}"
    );
    assert!(
        generated.contains(
            "INSERT INTO \\\"workspace_members\\\" (user_id, workspace_id, role) VALUES (1, 1, 'owner')"
        ),
        "membership row seeded for user 1: {generated}"
    );
    // The raw-SQL seed needs ConnectionTrait in scope.
    assert!(
        generated.contains("use jerrycan::db::sea_orm::ConnectionTrait;"),
        "{generated}"
    );

    // The tenant module ITSELF (workspaces) owns no tenant-owned entity, so its
    // test neither seeds nor provides the guard (no false coupling).
    let workspaces = design
        .modules
        .iter()
        .find(|m| m.name == "workspaces")
        .expect("workspaces module");
    let ws_gen = testgen::acceptance_rs(&design, workspaces);
    assert!(
        !ws_gen.contains(".provide_dep(shared::tenant)") && !ws_gen.contains("workspace_members"),
        "non-tenant-owned module needs no seed: {ws_gen}"
    );
}

/// A tenant-owned entity's create/update bodies must carry the fk column the
/// `belongs_to` derives, valued at the SEEDED tenant (workspace 1). WHY: without
/// it the generated request body is missing a NOT-NULL column, so the handler's
/// `Json<Lead>` deserialization rejects it 422 — the test fails before reaching
/// the stub, masking whether the handler is actually implemented. With the fk
/// present the request reaches the stub (500 on stubs → green when implemented).
#[test]
fn tenant_owned_fixtures_carry_the_foreign_key() {
    let s = include_str!("../../../conformance/designs/kolli-slice.design.json");
    let design: Design = serde_json::from_str(s).unwrap();
    let leads = design
        .modules
        .iter()
        .find(|m| m.name == "leads")
        .expect("leads module");
    let generated = testgen::acceptance_rs(&design, leads);
    // create_lead (POST /) and update_lead (PUT /{id}) both send a Lead body;
    // each must include the workspace_id fk valued at the seeded tenant (1).
    assert!(
        generated.contains("\"workspace_id\": 1"),
        "Lead fixture bodies must carry workspace_id: 1: {generated}"
    );

    // A non-tenant-owned entity's body must NOT gain a phantom fk.
    let workspaces = design
        .modules
        .iter()
        .find(|m| m.name == "workspaces")
        .expect("workspaces module");
    let ws_gen = testgen::acceptance_rs(&design, workspaces);
    assert!(
        !ws_gen.contains("\"workspace_id\""),
        "Workspace (the tenant itself) must not carry a self fk: {ws_gen}"
    );
}

/// A tenant-owned module with a creator + GET /{id} gets a cross-tenant
/// isolation test: user 1 creates a row in workspace 1, user 2 (workspace 2)
/// must NOT be able to read it. This is the security contract — it fails on
/// stubs (500) and stays red if the agent uses unscoped repo methods (which
/// would return the foreign row), going green only with scoped get_for.
#[test]
fn tenant_owned_modules_get_isolation_tests() {
    let s = include_str!("../../../conformance/designs/kolli-slice.design.json");
    let d: Design = serde_json::from_str(s).unwrap();
    let leads = d
        .modules
        .iter()
        .find(|m| m.name == "leads")
        .expect("leads module");
    let out = testgen::acceptance_rs(&d, leads);
    assert!(
        out.contains("async fn tenant_a_cannot_read_tenant_b_leads()"),
        "{out}"
    );
    assert!(out.contains("404"), "cross-tenant get must 404: {out}");
    // The isolation test seeds a SECOND tenant (workspace 2) + membership for
    // user 2, and mints user 2's cookie via the generalized helper.
    assert!(
        out.contains("fn seed_second_tenant(") && out.contains("test_cookie_for("),
        "isolation test needs a second-tenant seed + per-user cookie helper: {out}"
    );
    // test_cookie() stays back-compat (delegates to test_cookie_for(1)).
    assert!(
        out.contains("test_cookie_for(1)"),
        "test_cookie() must delegate to test_cookie_for(1): {out}"
    );
    // The DELETE leg is role-gated (owner); user 2's membership must seed the
    // owner role so the role check passes and the SCOPED remove_for 404s (proving
    // isolation, not a role rejection).
    assert!(
        out.contains("'owner'"),
        "second tenant membership seeds the owner role: {out}"
    );

    // The non-tenant-owned tenant module (workspaces) gets NO isolation test.
    let workspaces = d
        .modules
        .iter()
        .find(|m| m.name == "workspaces")
        .expect("workspaces module");
    let ws_gen = testgen::acceptance_rs(&d, workspaces);
    assert!(
        !ws_gen.contains("cannot_read_tenant_b"),
        "non-tenant-owned module gets no isolation test: {ws_gen}"
    );
}
